import type { Student } from '../types';

export const mockStudents: Student[] = [
  {
    "id": "1",
    "name": "Miles Stitch",
    "email": "stitchm26@allen-stevenson.org",
    "parentEmail1": "kstitch@wcapgroup.com",
    "parentEmail2": "matias.stitch@rothschildandco.com",
    "testType": "Upper Level SSAT",
    "targetScore": "Above 80th percentile",
    "rate": 240,
    "frequency": "1x",
    "startDate": "March 2024",
    "projectedEndDate": "Winter 2025"
  },
  {
    "id": "2",
    "name": "William Meyer",
    "email": "08wmeyer@gmail.com",
    "parentEmail1": "",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1400",
    "rate": 240,
    "frequency": "1x/week",
    "startDate": "6/18/2025",
    "projectedEndDate": "June 2026"
  },
  {
    "id": "3",
    "name": "Bobo Bonobo",
    "email": "charliekasov@gmail.com",
    "parentEmail1": "prayforchaos@hotmail.com",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "",
    "rate": undefined,
    "frequency": "",
    "startDate": "",
    "projectedEndDate": ""
  },
  {
    "id": "4",
    "name": "Arin Lee",
    "email": "erinmarialee@icloud.com",
    "parentEmail1": "jisunjamiekim@gmail.com",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1500+",
    "rate": 240,
    "frequency": "1-2x/week",
    "startDate": "6/14/2025",
    "projectedEndDate": "Fall 2025 (maybe Fall 2026)"
  },
  {
    "id": "5",
    "name": "Allison Yu",
    "email": "allisonyunyc@gmail.com",
    "parentEmail1": "allisonyunyc@gmail.com",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1600",
    "rate": 240,
    "frequency": "2x/week",
    "startDate": "6/19/2025",
    "projectedEndDate": "8/23/25"
  },
  {
    "id": "6",
    "name": "John DePaolo",
    "email": "jdepaolo@browning.edu",
    "parentEmail1": "elizabeth.quarta@gmail.com",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1500",
    "rate": 240,
    "frequency": "2-3x/week",
    "startDate": "6/23/2025",
    "projectedEndDate": "September 2025"
  },
  {
    "id": "7",
    "name": "Natalie Yu",
    "email": "natalieyunyc@gmail.com",
    "parentEmail1": "",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1550",
    "rate": 240,
    "frequency": "1x/week",
    "startDate": "6/25/2025",
    "projectedEndDate": "2027"
  },
  {
    "id": "8",
    "name": "Bobo Bonobo Baby Brother",
    "email": "charliekasov@gmail.com",
    "parentEmail1": "",
    "parentEmail2": "",
    "testType": "Upper Level SSAT",
    "targetScore": "90th percentile",
    "rate": undefined,
    "frequency": "",
    "startDate": "7/1/2025",
    "projectedEndDate": ""
  },
  {
    "id": "9",
    "name": "Lukas DiPasquale",
    "email": "lukasdip615@gmail.com",
    "parentEmail1": "",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1500+",
    "rate": 240,
    "frequency": "",
    "startDate": "7/8/2025",
    "projectedEndDate": ""
  },
  {
    "id": "10",
    "name": "Mia DiPasquale",
    "email": "miadip615@gmail.com",
    "parentEmail1": "",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1500+",
    "rate": 240,
    "frequency": "",
    "startDate": "7/8/2025",
    "projectedEndDate": ""
  },
  {
    "id": "11",
    "name": "Grant Ferguson",
    "email": "grantferg21@gmail.com",
    "parentEmail1": "",
    "parentEmail2": "",
    "testType": "SAT",
    "targetScore": "1600",
    "rate": 250,
    "frequency": "1x/week",
    "startDate": "7/14/2025",
    "projectedEndDate": "Fall 2025"
  }
];
